"""ChArUco board definition and detection.

The board is the world frame W for the whole calibration, so its physical
dimensions enter every downstream result as a scale factor. A printer that scales
by 2% puts a 2% error on every translation the calibration reports, and nothing
downstream can detect or correct it. Hence square_mm must be MEASURED on the
printed board with calipers, not copied from the file you sent to the printer.

Board geometry is stored in board.json so every stage agrees on it.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from dataclasses import fields as dataclass_fields
from pathlib import Path

import cv2
import numpy as np

CONFIG_FILE = Path(__file__).resolve().parent.parent / "board.json"


def _predefined() -> dict[str, int]:
    """Every DICT_* constant this OpenCV build offers.

    Enumerated rather than hard-coded so nothing a board might have been printed
    with is missing. Within a family the patterns are nested and identical for
    shared ids, so a board only needs a dictionary large enough to hold
    squares_x * squares_y / 2 markers.
    """
    out: dict[str, int] = {}
    for name in sorted(dir(cv2.aruco)):
        if name.startswith("DICT_"):
            value = getattr(cv2.aruco, name)
            if isinstance(value, int):
                out[name] = value
    return out


DICTIONARIES = _predefined()


def canonical_names() -> list[str]:
    """One name per distinct dictionary, for listing without duplicates.

    Some constants exist under two spellings (DICT_APRILTAG_36h11 and _36H11).
    Both remain accepted as input; only one is worth showing.
    """
    seen: dict[int, str] = {}
    for name in sorted(DICTIONARIES):
        value = DICTIONARIES[name]
        if value not in seen:
            seen[value] = name
    return sorted(seen.values())


def dictionary_size(name: str) -> int:
    """How many markers a dictionary holds."""
    d = cv2.aruco.getPredefinedDictionary(DICTIONARIES[name])
    return int(d.bytesList.shape[0])


@dataclass
class BoardSpec:
    """A physical ChArUco board.

    squares_x, squares_y : number of chessboard squares, not corners
    square_mm            : measured square edge length
    marker_mm            : measured ArUco marker edge length
    dictionary           : one of DICTIONARIES
    legacy               : True if the board was generated by OpenCV < 4.6
    name                 : free label, e.g. "big_world_board"

    The legacy flag is a property of the printed sheet, not a preference. OpenCV
    4.6 changed which squares carry markers and how they are numbered. Give the
    wrong value and marker detection still works perfectly while ChArUco corner
    matching returns nothing, which is a confusing way to fail. detect_geometry()
    determines it from an image.
    """

    squares_x: int
    squares_y: int
    square_mm: float
    marker_mm: float
    dictionary: str = "DICT_5X5_1000"
    legacy: bool = False
    name: str = "board"
    measured: bool = False

    def __post_init__(self):
        if self.dictionary not in DICTIONARIES:
            raise ValueError(
                f"unknown dictionary '{self.dictionary}'; "
                f"choose from {sorted(DICTIONARIES)}")
        if self.marker_mm >= self.square_mm:
            raise ValueError(
                f"marker ({self.marker_mm} mm) must be smaller than "
                f"square ({self.square_mm} mm)")
        if min(self.squares_x, self.squares_y) < 3:
            raise ValueError("board needs at least 3 squares on each side")

        # OpenCV builds an oversized board without complaining and reports ids it
        # cannot actually represent, so check the capacity here.
        needed = self.n_markers
        available = dictionary_size(self.dictionary)
        if needed > available:
            raise ValueError(
                f"a {self.squares_x}x{self.squares_y} board needs {needed} "
                f"markers but {self.dictionary} only holds {available}. "
                f"Use a larger dictionary from the same family, e.g. "
                f"{self._suggest_dictionary(needed)}.")

    def _suggest_dictionary(self, needed: int) -> str:
        """Smallest dictionary in the same family that can hold this board."""
        family = self.dictionary.rsplit("_", 1)[0]
        candidates = [(dictionary_size(n), n) for n in DICTIONARIES
                      if n.startswith(family + "_")]
        for size, name in sorted(candidates):
            if size >= needed:
                return name
        return "a larger marker size, e.g. DICT_5X5_1000"

    @property
    def n_markers(self) -> int:
        """Markers a ChArUco board of this size uses: half the squares."""
        return (self.squares_x * self.squares_y) // 2

    @property
    def square_m(self) -> float:
        return self.square_mm / 1000.0

    @property
    def marker_m(self) -> float:
        return self.marker_mm / 1000.0

    @property
    def n_corners(self) -> int:
        """Interior chessboard corners, which are what ChArUco actually detects."""
        return (self.squares_x - 1) * (self.squares_y - 1)

    @property
    def size_mm(self) -> tuple[float, float]:
        return (self.squares_x * self.square_mm, self.squares_y * self.square_mm)

    def cv_dictionary(self):
        return cv2.aruco.getPredefinedDictionary(DICTIONARIES[self.dictionary])

    def cv_board(self) -> cv2.aruco.CharucoBoard:
        board = cv2.aruco.CharucoBoard(
            (self.squares_x, self.squares_y),
            self.square_m, self.marker_m, self.cv_dictionary())
        board.setLegacyPattern(self.legacy)
        return board

    def corner_positions(self) -> np.ndarray:
        """Interior corner coordinates in board frame, metres, z = 0."""
        return np.asarray(self.cv_board().getChessboardCorners(), dtype=float)

    def describe(self) -> str:
        w, h = self.size_mm
        flag = "" if self.measured else "   <-- NOT MEASURED, results will carry a scale error"
        return (f"  {self.name}: {self.squares_x}x{self.squares_y} squares, "
                f"square {self.square_mm:.2f} mm, marker {self.marker_mm:.2f} mm\n"
                f"  {self.dictionary} ({dictionary_size(self.dictionary)} markers, "
                f"{self.n_markers} used), {self.n_corners} interior corners,\n"
                f"  printed size {w:.0f} x {h:.0f} mm{flag}")


class BoardDetector:
    """Detects a BoardSpec in images and reports corners plus board pose."""

    def __init__(self, spec: BoardSpec, min_corners: int = 6):
        self.spec = spec
        self.board = spec.cv_board()
        self.min_corners = min_corners
        params = cv2.aruco.CharucoParameters()
        params.tryRefineMarkers = True
        self.detector = cv2.aruco.CharucoDetector(self.board, params)

    def detect(self, image: np.ndarray) -> dict | None:
        """Find interior corners. Returns None when too few are visible."""
        gray = image if image.ndim == 2 else cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        corners, ids, _, _ = self.detector.detectBoard(gray)
        if corners is None or ids is None or len(ids) < self.min_corners:
            return None
        return {
            "corners": np.asarray(corners, dtype=float).reshape(-1, 2),
            "ids": np.asarray(ids, dtype=int).reshape(-1),
            "n": int(len(ids)),
        }

    def match_points(self, corners: np.ndarray, ids: np.ndarray):
        """Corner detections -> (object points, image points) for calibration."""
        obj, img = self.board.matchImagePoints(
            corners.reshape(-1, 1, 2).astype(np.float32),
            ids.reshape(-1, 1).astype(np.int32))
        if obj is None or img is None:
            return None, None
        return obj.reshape(-1, 3), img.reshape(-1, 2)

    def solve_pose(self, detection: dict, K: np.ndarray, dist: np.ndarray):
        """Board pose in camera frame as T_cam_board, or None if PnP fails.

        Needs at least 4 corners for a unique solution; below 6 the pose is
        typically too noisy to be worth using, hence min_corners.
        """
        obj, img = self.match_points(detection["corners"], detection["ids"])
        if obj is None or len(obj) < 4:
            return None

        ok, rvec, tvec, inliers = cv2.solvePnPRansac(
            obj.astype(np.float64), img.astype(np.float64),
            K, dist, flags=cv2.SOLVEPNP_ITERATIVE,
            reprojectionError=3.0, confidence=0.999, iterationsCount=200)
        if not ok:
            return None

        # Refine on the inlier set; RANSAC alone stops at the first good model.
        if inliers is not None and len(inliers) >= 4:
            idx = inliers.reshape(-1)
            rvec, tvec = cv2.solvePnPRefineLM(
                obj[idx].astype(np.float64), img[idx].astype(np.float64),
                K, dist, rvec, tvec)

        from . import se3
        T = se3.make_transform(se3.exp_so3(rvec.reshape(3)), tvec.reshape(3))
        n_in = len(obj) if inliers is None else len(inliers)
        return {"T_cam_board": T, "n_inliers": int(n_in), "n_points": int(len(obj)),
                "rvec": rvec.reshape(3), "tvec": tvec.reshape(3)}

    def reprojection_error(self, detection, K, dist, rvec, tvec) -> float:
        """RMS reprojection error in pixels for one view."""
        obj, img = self.match_points(detection["corners"], detection["ids"])
        if obj is None:
            return float("nan")
        proj, _ = cv2.projectPoints(obj.astype(np.float64), rvec, tvec, K, dist)
        diff = proj.reshape(-1, 2) - img
        return float(np.sqrt(np.mean(np.sum(diff ** 2, axis=1))))


def _marker_centres(spec: BoardSpec) -> dict[int, np.ndarray]:
    """Board-frame centre of every marker, keyed by marker id."""
    out = {}
    for i, pts in enumerate(spec.cv_board().getObjPoints()):
        out[i] = np.asarray(pts).reshape(-1, 3)[:, :2].mean(axis=0)
    return out


def _layout_residual(image: np.ndarray, spec: BoardSpec) -> dict | None:
    """How well a candidate board explains the markers seen in an image.

    Fits a homography from the candidate's model marker layout onto the detected
    marker centres. A board flat in front of a camera is related to its image by
    exactly one homography, so the correct geometry leaves a sub-pixel residual
    while a wrong one cannot be reconciled by any projective transform.
    """
    gray = image if image.ndim == 2 else cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    detector = cv2.aruco.ArucoDetector(spec.cv_dictionary(),
                                       cv2.aruco.DetectorParameters())
    corners, ids, _ = detector.detectMarkers(gray)
    if ids is None or len(ids) < 8:
        return None

    model = _marker_centres(spec)
    src, dst = [], []
    for k, marker_id in enumerate(ids.ravel()):
        centre = model.get(int(marker_id))
        if centre is not None:
            src.append(centre)
            dst.append(np.asarray(corners[k]).reshape(-1, 2).mean(axis=0))
    if len(src) < 8:
        return None

    src = np.asarray(src, dtype=np.float64)
    dst = np.asarray(dst, dtype=np.float64)
    H, mask = cv2.findHomography(src, dst, cv2.RANSAC, 5.0)
    if H is None:
        return None

    projected = cv2.perspectiveTransform(src.reshape(-1, 1, 2), H).reshape(-1, 2)
    error = np.linalg.norm(projected - dst, axis=1)
    inliers = int(mask.sum()) if mask is not None else len(error)
    return {
        "matched": len(src),
        "inliers": inliers,
        "inlier_fraction": inliers / len(src),
        "median_px": float(np.median(error)),
        "rms_px": float(np.sqrt(np.mean(error ** 2))),
    }


def detect_geometry(image: np.ndarray, square_mm: float, marker_mm: float,
                    dictionary: str, candidates: list[tuple[int, int]],
                    name: str = "board") -> list[dict]:
    """Work out a board's real geometry from an image of it.

    Tries each candidate square count both ways round and with the legacy flag
    both ways, ranking by how well the marker layout fits. Returns every option
    scored, best first, so the caller can see the margin rather than trusting a
    single answer.

    This exists because a printed board's label tells you the dictionary and often
    the square count, but never the orientation convention or the legacy flag, and
    getting either wrong detects markers happily while finding no ChArUco corners.
    """
    scored = []
    seen = set()
    for (sx, sy) in candidates:
        for (a, b) in {(sx, sy), (sy, sx)}:
            for legacy in (False, True):
                if (a, b, legacy) in seen:
                    continue
                seen.add((a, b, legacy))
                try:
                    spec = BoardSpec(squares_x=a, squares_y=b,
                                     square_mm=square_mm, marker_mm=marker_mm,
                                     dictionary=dictionary, legacy=legacy,
                                     name=name)
                except ValueError:
                    continue  # too big for the dictionary
                result = _layout_residual(image, spec)
                if result is None:
                    continue
                result.update({"squares_x": a, "squares_y": b, "legacy": legacy,
                               "spec": spec})
                scored.append(result)

    # Prefer a clean fit over a large one: a wrong geometry can match many markers
    # while placing them badly.
    scored.sort(key=lambda r: (-r["inlier_fraction"], r["median_px"]))
    return scored


def save_boards(boards: dict[str, BoardSpec], path: Path = CONFIG_FILE) -> None:
    payload = {name: asdict(spec) for name, spec in boards.items()}
    path.write_text(json.dumps(payload, indent=2) + "\n")


def load_boards(path: Path = CONFIG_FILE) -> dict[str, BoardSpec]:
    if not path.is_file():
        return {}
    raw = json.loads(path.read_text())
    fields = {f.name for f in dataclass_fields(BoardSpec)}
    boards = {}
    for name, entry in raw.items():
        # Ignore keys this version does not know, so a file written by a newer
        # version degrades instead of crashing every stage that reads it.
        boards[name] = BoardSpec(**{k: v for k, v in entry.items() if k in fields})
    return boards


def render(spec: BoardSpec, dpi: int = 300, margin_mm: float = 10.0) -> np.ndarray:
    """Printable board image at a given DPI, with a quiet margin."""
    px_per_mm = dpi / 25.4
    w = int(round(spec.squares_x * spec.square_mm * px_per_mm))
    h = int(round(spec.squares_y * spec.square_mm * px_per_mm))
    img = spec.cv_board().generateImage((w, h))
    m = int(round(margin_mm * px_per_mm))
    return cv2.copyMakeBorder(img, m, m, m, m, cv2.BORDER_CONSTANT, value=255)
