// Dashboard behaviour. Served by GET /dashboard.js, which substitutes
// __STRINGS__ before sending, so the phrase table is present on first
// paint. Kept out of app.py because the page template there is a Python
// string: an editor cannot check this as JavaScript, and a stray quote is
// invisible until the page fails in a browser.
let data=null,selected=null,confirming=false,startup=null,guidedShortcut=null,guidedSending=false,guidedKeyboardClickAt=0,liveInteractionToken='';const FINAL_STAGE='verify';const autoCommitting=new Set(),autoCommitFailed=new Set();
const STRINGS=__STRINGS__;
// One phrase, with {placeholders} filled in. An unknown key shows itself, so a
// missing phrase is visible rather than silently blank.
function T(key,fields){let out=STRINGS[key];if(out===undefined)return key;if(fields)for(const k in fields)out=out.split('{'+k+'}').join(fields[k]);return out}
const labels={blocked:T('status.blocked'),ready:T('status.ready'),completed:T('status.completed'),completed_large_error:T('status.completedLargeError'),stale:T('status.stale'),authorized:T('status.authorized'),running:T('status.running'),review:T('status.review'),failed:T('status.failed'),cancelled:T('status.cancelled')};
// Stage 8 that missed its accuracy gates is still finished: it offers the same
// actions as a clean pass, and only the badge and the reason differ.
const DONE_STATES=['completed','completed_large_error','stale'];
async function api(path,opts={}){const r=await fetch(path,{cache:'no-store',...opts});const text=await r.text();let body;try{body=JSON.parse(text)}catch{throw new Error(text||`HTTP ${r.status}`)}if(!r.ok)throw new Error(body.error||`HTTP ${r.status}`);return body}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setStageOpen(on){const el=document.getElementById('layout');if(el)el.classList.toggle('stage-open',!!on)}
function render(){setStageOpen(false);guidedShortcut=null;workspace.textContent=data.workspace;const recommended=data.recommended&&data.recommended.key;if(!selected)selected=recommended||data.stages[0].key;stages.innerHTML=data.stages.map(s=>`<button class="stage ${s.key===selected?'active':''}" onclick="selectStage('${s.key}')"><span class="num">${s.number}</span><span><strong>${esc(s.title)}</strong><br><small class="muted">${esc(s.reason)}</small></span><span class="badge ${s.state}">${labels[s.state]||s.state}</span></button>`).join('');const s=data.stages.find(x=>x.key===selected);const missing=s.missing.length?`<div class="reason"><strong>${T('ui.needFirst')}</strong><div class="files">${s.missing.map(x=>`<span class="file">${esc(x)}</span>`).join('')}</div></div>`:'';let action='';if(s.hardware&&(!startup||!startup.passed))action=`<button class="action primary" disabled>${T('ui.startupFirst')}</button>`;else if(s.state==='blocked')action=`<button class="action primary" disabled>${T('ui.notYet')}</button>`;else if(DONE_STATES.includes(s.state))action=(s.key===FINAL_STAGE?'':`<button class="action" onclick="viewResult()">${T('stage.viewResult')}</button>`)+`<button class="action" onclick="showRerun()">${T('ui.archiveRerun')}</button>`;else if(['authorized','running'].includes(s.state))action=`<button class="action primary" onclick="continueRun()">${T('ui.openTask')}</button><button class="action" onclick="cancelRun()">${T('ui.endRun')}</button>`;else if(s.state==='review')action=autoCommitFailed.has(s.key)?`<button class="action primary" onclick="autoCommitStage('${s.key}',true)">${T('ui.retryCommit')}</button><button class="action" onclick="continueRun()">${T('ui.viewTask')}</button><button class="action" onclick="cancelRun()">${T('ui.abandonRun')}</button>`:`<button class="action primary" disabled>${T('ui.autoSaving')}</button>`;else action=`<button class="action primary" onclick="start(false)">${T('stage.start',{number:s.number})}</button>`;main.innerHTML=`${recommended===s.key?'<div class="current"><strong>'+T('ui.suggested')+'</strong><div>'+esc(T('ui.suggestedBody',{number:s.number,title:s.title}))+'</div></div>':''}<h2>${esc(T('stage.number',{number:s.number}))} · ${esc(s.title)}</h2><div class="muted">${esc(s.reason)}</div>${s.notice?`<div class="caution">${esc(s.notice)}</div>`:''}<div class="steps"><div class="step"><strong>${T('stage.why')}</strong>${esc(s.purpose||T('stage.defaultPurpose'))}</div><div class="step"><strong>${T('stage.what')}</strong>${esc(s.action)}</div><div class="step"><strong>${T('stage.when')}</strong>${esc(s.completion)}</div></div>${missing}<div class="reason"><strong>${T('stage.outputs')}</strong><div class="files">${s.outputs.map(x=>`<span class="file">${esc(x)}</span>`).join('')}</div></div><div class="actions">${action}</div><div id="message"></div>`;if(s.key===FINAL_STAGE&&DONE_STATES.includes(s.state))showFinalResult(s.key)}
async function showFinalResult(key){const host=document.getElementById('message');if(!host)return;host.innerHTML=`<p class="muted">${T('ui.loadingResult')}</p>`;try{const summary=await api(`/api/stages/${key}/summary`);if(selected!==key)return;const target=document.getElementById('message');if(target)target.innerHTML=renderResultSummary(summary)+'<p class="success">'+T('ui.resultSaved')+'</p>'}catch(e){if(selected!==key)return;const target=document.getElementById('message');if(target)target.innerHTML=`<p class="error">${esc(T('ui.summaryFailed',{message:e.message}))}</p><button class="action" onclick="showFinalResult('${key}')">${T('ui.retry')}</button>`}}
function renderStartup(){if(!startup)return;startupTitle.textContent=T('ui.startupHeading');if(startup.passed){startupChecks.innerHTML='<div class="success">'+T('startup.pass')+'</div>';startup.className='startup ok';return}const failed=startup.checks.filter(c=>!c.passed);startupChecks.innerHTML=failed.map(c=>`<div class="check"><strong class="error">${T('ui.checkFailed')}</strong><div>${esc(c.message)}</div>${c.fix?`<small class="muted">${esc(c.fix)}</small>`:''}</div>`).join('');startup.className='startup failed';}
async function identifyCameras(){startupChecks.innerHTML='<p class="muted">'+T('ui.cameraToolStarting')+'</p>';try{await api('/api/cameras/identify',{method:'POST'});setStageOpen(true);main.innerHTML='<div class="stage-head"><div><strong>'+T('ui.cameraToolTitle')+'</strong><div class="muted">'+T('ui.cameraToolNote')+'</div></div><div class="actions"><button class="action primary" onclick="finishCameras()">'+T('ui.cameraToolDone')+'</button></div></div><iframe title="'+T('ui.cameraToolTitle')+'" class="stage-frame" src="/cameras/"></iframe>'}catch(e){renderStartup();showError(e.message)}}
async function finishCameras(){try{await api('/api/cameras/stop',{method:'POST'})}catch(e){}setStageOpen(false);await runStartupChecks(true);await refresh()}
// Only say "checking" when the hardware is really being looked at again, or on
// the very first run. Re-wording an already-known verdict is instant, and
// blanking the panel for it made a passing robot flash as though it had failed.
async function runStartupChecks(refresh){if(refresh||!startup){startupChecks.textContent=T('ui.startupChecking')}try{startup=await api('/api/startup-checks'+(refresh?'?refresh=1':''));renderStartup();render()}catch(e){startupChecks.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function selectStage(k){selected=k;confirming=false;render()}
function showRerun(){if(confirming)return;confirming=true;const s=data.stages.find(x=>x.key===selected);message.innerHTML=`<div class="confirm"><strong>${T('ui.rerunTitle')}</strong><p>${T('ui.rerunBody')}</p><div class="actions"><button class="action primary" onclick="start(true)">${T('ui.rerunConfirm')}</button><button class="action" onclick="selectStage('${s.key}')">${T('ui.cancel')}</button></div></div>`}
async function start(rerun){try{const current=data.stages.find(x=>x.key===selected);if(current.hardware&&!startup){message.innerHTML='<p class="error">'+T('ui.startupPending')+'</p>';return}if(current.hardware&&!startup.passed){message.innerHTML='<p class="error">'+T('ui.startupBlocked')+'</p>';return}const r=await api(`/api/stages/${selected}/authorize`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rerun})});await refresh();if(r.runtime)continueRun();else message.innerHTML='<p class="success">'+T('ui.authorized')+'</p>'}catch(e){message.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function viewResult(){try{const summary=await api(`/api/stages/${selected}/summary`);message.innerHTML=renderResultSummary(summary)+ '<p class="success">'+T('ui.resultSaved')+'</p>'}catch(e){message.innerHTML=`<p class="error">${esc(T('ui.summaryFailed',{message:e.message}))}</p>`}}
function cell(x){if(x&&typeof x==='object'&&x.link)return `<a href="${esc(x.link)}" target="_blank" rel="noopener">${esc(x.text||x.link)}</a>`;return esc(x)}
function renderResultSummary(summary){const sections=(summary.sections||[]).map(section=>{const body=section.svg?`<div class="summary-figure">${section.svg}</div>`:`<div class="summary-scroll"><table><thead><tr>${section.columns.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${section.rows.map(row=>`<tr>${row.map(x=>`<td>${cell(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;return `<section class="result-summary"><h3>${esc(section.title)}</h3>${body}</section>`}).join('');return `<div class="result-summary-wrap"><h3>${esc(T('stage.resultTitle',{number:summary.stage_number,title:summary.title}))}</h3>${sections}</div>`}
async function continueRun(){try{const r=await api('/api/runtime');if(r.phase==='review'){setStageOpen(false);main.innerHTML=`<div class="current"><strong>${T('ui.stageDone')}</strong><div>${T('ui.stageDoneBody')}</div></div>`;await autoCommitStage(r.progress.stage)}else if(r.progress&&r.progress.interactive){setStageOpen(false);renderInteraction(r)}else if(r.progress&&r.progress.port){setStageOpen(true);main.innerHTML='<div class="stage-head"><div><strong>'+T('ui.stageTask')+'</strong></div><div class="actions"><button class="action" onclick="setStageOpen(false);refresh()">'+T('ui.showStages')+'</button><button class="action" onclick="cancelRun()">'+T('ui.endRun')+'</button></div></div><iframe title="'+T('ui.stageFrame')+'" class="stage-frame" src="/stage/"></iframe>'}else{setStageOpen(false);main.innerHTML=`<div class="current"><strong>${T('ui.computing')}</strong><div>${esc(r.message)}</div></div><p class="muted">${T('ui.computingNote')}</p><div class="actions"><button class="action" onclick="cancelRun()">${T('ui.endRun')}</button></div>`}}catch(e){setStageOpen(false);main.innerHTML=`<p class="error">${esc(e.message)}</p><button class="action" onclick="refresh()">${T('ui.backToFlow')}</button>`}}
function renderLiveRanges(live){if(!live||!live.joints||!live.joints.length)return '';const rows=live.joints.map(j=>{const ok=j.enough?'<span class="ok-mark">'+T('ranges.enough')+'</span>':'<span class="short-mark">'+T('ranges.short')+'</span>';const notes=[];if(j.wrapped)notes.push(T('ranges.wrapped'));if(j.over_one_turn)notes.push(T('ranges.overTurn'));const allowed=j.allowed_deg==null?'—':j.allowed_deg.toFixed(0)+'°';return `<tr><th>${esc(j.label)}</th><td>${j.raw==null?'—':j.raw}</td><td>${j.position_deg.toFixed(1)}°</td><td>${j.min_deg.toFixed(1)}°</td><td>${j.max_deg.toFixed(1)}°</td><td>${j.span_deg.toFixed(1)}°</td><td>${allowed}</td><td>${ok}${notes.length?'<br><small class="muted">'+esc(notes.join(T('ui.noteJoin')))+'</small>':''}</td></tr>`}).join('');return `<section class="measurements"><h3>${T('ranges.heading')}</h3><p class="muted">${T('ranges.blurb')}</p><table><thead><tr><th>${T('ranges.joint')}</th><th>${T('ranges.raw')}</th><th>${T('ranges.current')}</th><th>${T('ranges.min')}</th><th>${T('ranges.max')}</th><th>${T('ranges.covered')}</th><th>${T('ranges.allowed')}</th><th>${T('ranges.status')}</th></tr></thead><tbody>${rows}</tbody></table></section>`}
function renderMeasurements(items){if(!items||!items.length)return '';if(items[0].raw!==undefined){const rows=items.map(m=>`<tr><th>${esc(m.label)}</th><td>${esc(m.joint)}</td><td>${m.raw} counts</td></tr>`).join('');return `<section class="measurements"><h3>${T('ui.roughZeroTitle')}</h3><p class="muted">${T('ui.roughZeroNote')}</p><table><thead><tr><th>${T('ranges.joint')}</th><th>${T('ui.name')}</th><th>${T('ranges.raw')}</th></tr></thead><tbody>${rows}</tbody></table></section>`}const rows=items.map(m=>`<tr><th>${esc(m.label)}</th><td>${m.start_raw==null?T('ui.waitingRead'):m.start_raw+' counts'}</td><td>${m.end_raw==null?T('ui.waitingMove'):m.end_raw+' counts'}</td><td>${m.travel_counts==null?T('ui.waitingTravel'):m.travel_counts+' counts'}</td><td>${m.travel_deg==null?'—':m.travel_deg.toFixed(1)+'°'}</td><td>${m.sense==null?T('ui.waitingSense'):(m.sense>0?'+1':'-1')}</td></tr>`).join('');return `<section class="measurements"><h3>${T('ui.liveTitle')}</h3><table><thead><tr><th>${T('ranges.joint')}</th><th>${T('measure.start')}</th><th>${T('measure.end')}</th><th>${T('ui.diffCounts')}</th><th>${T('ui.diffDeg')}</th><th>${T('sum.senses.sign')}</th></tr></thead><tbody>${rows}</tbody></table></section>`}
function renderReference(ref){if(!ref||(!ref.note&&(!ref.steps||!ref.steps.length)))return '';const rows=(ref.steps||[]).map(s=>`<tr><th>${esc(s.joint)}</th><td>${esc(s.detail)}</td></tr>`).join('');return `<div class="reference"><h3>${esc(ref.title||T('ui.reference'))}</h3>${rows?`<table class="reftable">${rows}</table>`:''}${ref.note?`<p class="refnote">${esc(ref.note)}</p>`:''}</div>`}
function renderInteraction(r){const step=(r.progress&&r.progress.interaction)||{};const primary=(step.buttons||[]).find(b=>b.kind==='primary');guidedShortcut=primary?{value:primary.value,token:step.token}:null;const buttons=(step.buttons||[]).map(b=>`<button class="action ${b.kind==='primary'?'primary':''}" ${guidedSending?'disabled':''} onclick="guidedClick('${encodeURIComponent(b.value)}','${step.token||''}')">${esc(b.label)}${b.kind==='primary'?T('ui.shortcutHint'):''}</button>`).join('');const measurements=r.progress&&r.progress.measurements||[];const live=r.progress&&r.progress.live_ranges;liveInteractionToken=step.token||'';main.innerHTML=`<div class="interaction"><h2>${esc(step.title||T('ui.preparing'))}</h2><p>${esc(step.instruction||r.message)}</p>${step.caution?`<div class="caution">${esc(step.caution)}</div>`:''}${renderReference(step.reference)}<div class="actions">${buttons}<button class="action" onclick="cancelRun()">${T('ui.endRun')}</button></div></div>${renderMeasurements(measurements)}<div id="liveRanges">${renderLiveRanges(live)}</div><details class="log"><summary>${T('ui.viewLog')}</summary><pre>${esc((r.progress&&r.progress.log_tail)||T('ui.noLog'))}</pre></details>`}
function guidedClick(encoded,token){if(Date.now()-guidedKeyboardClickAt<500){guidedKeyboardClickAt=0;return}sendGuidedInput(encoded,token)}
async function sendGuidedInput(encoded,token){if(guidedSending)return;guidedSending=true;guidedShortcut=null;let next=null;try{const key=selected;const value=decodeURIComponent(encoded);next=await api(`/api/stages/${key}/input`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value,interaction_token:token})});if(next.phase==='review')await autoCommitStage(key)}catch(err){showError(err.message)}finally{guidedSending=false;if(next&&next.phase!=='review')renderInteraction(next)}}
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.code==='Space')&&!event.repeat&&guidedShortcut!==null&&!guidedSending){const target=event.target;if(target&&['INPUT','TEXTAREA','SELECT'].includes(target.tagName))return;event.preventDefault();guidedKeyboardClickAt=Date.now();const action=guidedShortcut;sendGuidedInput(encodeURIComponent(action.value),action.token)}});
function showError(text){const target=document.getElementById('message')||document.getElementById('main');if(target)target.innerHTML=`<p class="error">${esc(text)}</p>`}
async function autoCommitStage(key,retry=false){if(!key||autoCommitting.has(key)||(!retry&&autoCommitFailed.has(key)))return;autoCommitting.add(key);try{await api(`/api/stages/${key}/commit`,{method:'POST'});autoCommitFailed.delete(key);selected=null;await refresh()}catch(e){autoCommitFailed.add(key);const stage=data&&data.stages.find(x=>x.key===key);await refresh();showError(T('ui.commitFailed',{number:stage?stage.number:T('ui.currentStage'),message:e.message}))}finally{autoCommitting.delete(key)}}
window.addEventListener('message',event=>{if(event.origin===window.location.origin&&event.data&&event.data.type==='stage-completed'){autoCommitStage(event.data.stage)}});
async function cancelRun(){try{await api(`/api/stages/${selected}/cancel`,{method:'POST'});await refresh()}catch(e){showError(e.message)}}
async function monitorRuntime(){try{const r=await api('/api/runtime');if(r.phase==='review'&&r.progress&&r.progress.stage){await autoCommitStage(r.progress.stage);return}
// The sweep table must keep up with the operator's hand, but re-rendering the
// whole prompt every tick would flicker and drop the keyboard shortcut. Only
// the table is replaced, and only while the same prompt is on screen.
const holder=document.getElementById('liveRanges');const step=(r.progress&&r.progress.interaction)||{};if(holder&&r.progress&&r.progress.interactive&&(step.token||'')===liveInteractionToken&&!guidedSending){holder.innerHTML=renderLiveRanges(r.progress.live_ranges)}}catch(e){}}
// The mounting is a property of the whole run, so it sits above the stage list
// rather than inside any stage. Switching is deliberately two steps: ask what it
// would cost, show that, and only then commit. Nothing measured one way up
// survives the switch, so silently discarding it would be unkind.
function renderMounting(){const now=document.getElementById('mountingNow');const acts=document.getElementById('mountingActions');if(!now||!acts||!data)return;now.textContent=T('mounting.now',{label:data.mountingLabel});acts.innerHTML=[['normal',T('mounting.normal')],['flipped',T('mounting.flipped')]].map(([key,label])=>`<button class="action ${data.mounting===key?'on':''}" onclick="askMounting('${key}')">${esc(label)}</button>`).join('')}
async function askMounting(target){if(!data||data.mounting===target)return;let plan;try{plan=await api('/api/mounting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mounting:target,preview:true})})}catch(e){showError(e.message);return}
const lost=plan.titles&&plan.titles.length?`<p>${esc(T('mounting.confirmBody',{current:data.mounting,target}))}</p><div class="files">${plan.titles.map(t=>`<span class="file">${esc(t)}</span>`).join('')}</div>`:`<p>${T('mounting.confirmNone')}</p>`;setStageOpen(false);main.innerHTML=`<div class="confirm"><strong>${T('mounting.confirmTitle')}</strong>${lost}<div class="actions"><button class="action primary" onclick="commitMounting('${target}')">${T('mounting.confirmGo')}</button><button class="action" onclick="refresh()">${T('mounting.cancel')}</button></div></div>`}
async function commitMounting(target){try{await api('/api/mounting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mounting:target})});selected=null;await refresh();const host=document.getElementById('message');if(host)host.innerHTML=`<p class="success">${esc(T('mounting.switched',{label:data.mountingLabel}))}</p>`}catch(e){showError(e.message)}}
async function refresh(){try{data=await api('/api/workflow');render();renderMounting();const current=data.stages.find(x=>x.state==='review');if(current)autoCommitStage(current.key)}catch(e){main.innerHTML=`<p class="error">${esc(T('ui.loadFailed',{message:e.message}))}</p>`}}
async function boot(){await refresh();await runStartupChecks();setInterval(monitorRuntime,400)}
boot();
